language: d
dist: jammy

d:
    - dmd
    - ldc

script:
    - wget https://www.openssl.org/source/openssl-3.0.12.tar.gz
    - tar xzvf openssl-3.0.12.tar.gz >/dev/null
    - cd openssl-3.0.12
    - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' >/dev/null
    - make >/dev/null
    - sudo make install >/dev/null
    - openssl version -a
    - cd ../
    - LD_LIBRARY_PATH=/usr/local/lib dub test --config=library --compiler=$DC
